spring:
  application:
    name: gestion-asignaturas-ms
  datasource:
    url: jdbc:mysql://localhost:3306/db_maestria_final
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL=debug: debug
server:
  port: 8021